services:
  mysqlusers:
    image: mysql:8
    container_name: mysqlusers  # Changé pour éviter les conflits
    ports:
      - "3307:3306"  # Changé pour éviter les conflits avec d'autres services MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: users_db
      MYSQL_USER: users_user
      MYSQL_PASSWORD: users_password
    volumes:
      - users_db_data:/var/lib/mysql  # Renommé pour éviter les conflits

  users:  # Renommé de 'hospital' à 'users' pour plus de clarté
    build: .
    container_name: users
    ports:
      - "8091:8082"  # Changé pour éviter les conflits
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlusers:3306/users_db  # Mis à jour pour correspondre au nouveau nom du container
    depends_on:
      - mysqlusers

volumes:
  users_db_data:  # Renommé pour éviter les conflits